/**
 * Copyright (c) 2026 EqualByte
 * All rights reserved.
 *
 * Core types for the Capability layer.
 *
 * @remarks
 * The Capability Registry — not WebMCP — is the core of the agentic architecture.
 * WebMCP, API calls, DOM automation and remote MCP are all *adapters* that back a
 * capability's `execute`. The planner only ever sees `name`, `description` and
 * `inputSchema`; the Execution Engine handles everything else.
 *
 * This package deliberately has no LLM and no DOM dependency so that capabilities
 * can be registered, resolved and policed in isolation (and unit-tested in Node).
 */

/**
 * Minimal JSON Schema shape used across the capability layer.
 *
 * @remarks
 * Capabilities speak JSON Schema rather than Zod because that is what WebMCP
 * (and MCP generally) exchanges on the wire. Internal tools authored with Zod are
 * converted at the boundary — see `@eb-agent/core`'s capability bridge.
 */
export interface JSONSchema {
	type?: string
	properties?: Record<string, JSONSchema>
	required?: string[]
	items?: JSONSchema
	enum?: unknown[]
	description?: string
	default?: unknown
	[key: string]: unknown
}

/**
 * Where a capability came from.
 *
 * @remarks
 * Ordering matters — see {@link SOURCE_PRIORITY}. A capability discovered natively
 * (the site declared it through WebMCP) always beats one we inferred ourselves.
 */
export type CapabilitySource =
	/** The application declared it itself via `document.modelContext`. */
	| 'native_webmcp'
	/** The application developer declared it via `ebAgent.registerTool()`. */
	| 'developer_defined'
	/** Provided by a configured remote MCP server (§19). */
	| 'remote_mcp'
	/** Inferred from an observed HTTP/GraphQL API (§18). */
	| 'api'
	/** Generated from the page's own UI by the DOM scanner. */
	| 'dom'
	/** Generated by some other inference pass. */
	| 'generated'

/**
 * How a capability is actually carried out. The planner never sees this.
 */
export type ExecutionType = 'webmcp' | 'javascript' | 'api' | 'dom' | 'remote_mcp'

/**
 * Risk classification driving the policy engine.
 *
 * - `read` — no state change. Normally executed automatically.
 * - `reversible` — changes state, but undoable. Executed automatically by default, always logged.
 * - `consequential` — acts in the user's name (payment, deletion, email). Requires explicit approval.
 */
export type RiskLevel = 'read' | 'reversible' | 'consequential'

/**
 * Relative trust of each source. Higher wins during deduplication.
 *
 * @remarks
 * Ordering follows §11, with remote MCP slotted between developer-defined and
 * inferred APIs: a configured MCP server is a real, declared backend contract
 * (so it beats anything we reverse-engineered), but the application's own
 * in-page declarations still know more about the current UI state.
 */
export const SOURCE_PRIORITY: Record<CapabilitySource, number> = {
	native_webmcp: 100,
	developer_defined: 80,
	remote_mcp: 70,
	api: 60,
	dom: 40,
	generated: 20,
}

/**
 * Agent-facing hints, mirroring WebMCP's `annotations`.
 * @see https://developer.chrome.com/docs/ai/webmcp/secure-tools
 */
export interface CapabilityAnnotations {
	/** Tool does not change state. Derived from `risk === 'read'` when unset. */
	readOnlyHint?: boolean
	/** Tool returns user-generated or third-party content — treat the result as untrusted. */
	untrustedContentHint?: boolean
}

/** Per-invocation context handed to `Capability.execute`. */
export interface CapabilityContext {
	/** Cooperative cancellation. Implementations MUST honor it. */
	signal: AbortSignal
}

/**
 * The result of running a capability.
 *
 * @remarks
 * Normalized to a plain string for the planner. `structured` carries the raw
 * payload when an adapter has one (e.g. a WebMCP content array or an API response),
 * so richer consumers don't lose it.
 */
export interface CapabilityResult {
	content: string
	structured?: unknown
	/** Set when the producing capability (or the site) flagged the payload as untrusted. */
	untrusted?: boolean
}

/**
 * A single thing the current application can do.
 *
 * @see §20 of the WebMCP Architecture Enhancement brief.
 */
export interface Capability<TInput = any> {
	/** Stable within a registry. Generated from `name` + `source` when omitted at registration. */
	id: string
	/** Business-action name, e.g. `search_customer`. Max 30 chars once normalized. */
	name: string
	/** What the capability does, in plain language. Max 500 chars once normalized. */
	description: string
	inputSchema: JSONSchema
	outputSchema?: JSONSchema
	source: CapabilitySource
	executionType: ExecutionType
	risk: RiskLevel
	/**
	 * How sure we are that this capability is real and correctly modeled, 0..1.
	 * Declared capabilities are 1. Generated ones are scored by the generator.
	 * Low-confidence capabilities stay internal instead of being published (§10).
	 */
	confidence: number
	/** URL (or route) this capability belongs to. Undefined means "valid app-wide". */
	page?: string
	version?: string
	annotations?: CapabilityAnnotations
	execute: (input: TInput, ctx: CapabilityContext) => Promise<CapabilityResult>
}

/** What a caller supplies to register a capability. `id` and `confidence` are filled in. */
export type CapabilityInput<TInput = any> = Omit<Capability<TInput>, 'id' | 'confidence'> & {
	id?: string
	confidence?: number
}

/**
 * Audit record emitted for every execution attempt (§17).
 * Enterprise governance and debugging both read this.
 */
export interface AuditEvent {
	user?: string
	session: string
	tool: string
	capabilityId: string
	arguments: unknown
	executionType: ExecutionType
	source: CapabilitySource
	risk: RiskLevel
	/** `true`/`false` when an approval decision was taken, `undefined` when none was required. */
	approved?: boolean
	startTime: number
	durationMs: number
	status: 'success' | 'error' | 'denied'
	result?: string
	error?: string
	page?: string
}

/** Decision returned by the policy engine before anything runs. */
export interface PolicyDecision {
	allowed: boolean
	requiresApproval: boolean
	/** Populated when `allowed` is false. Surfaced to the model so it can adapt. */
	reason?: string
}

/**
 * Asks a human to approve a consequential action (§16).
 * Resolve `true` to proceed. Must reject when `signal` aborts.
 */
export type ApprovalHandler = (
	request: {
		capability: Capability
		input: unknown
		/** Pre-rendered, human-readable summary of what is about to happen. */
		summary: string
	},
	options: { signal: AbortSignal }
) => Promise<boolean>

/**
 * Where a capability stands in the customer's review (§24).
 *
 * @remarks
 * Generated capabilities are inferences. `pending` ones are usable by eb-agent's
 * own planner but are never published to external agents until a human has looked
 * at them; `rejected` ones are withheld entirely.
 */
export type ReviewState = 'approved' | 'pending' | 'rejected'

/** A customer's decision about one generated capability. */
export interface CapabilityReview {
	capabilityId: string
	state: ReviewState
	/** Customer-supplied replacements for the generated name/description. */
	name?: string
	description?: string
	/** Customer override of the inferred risk level. */
	risk?: RiskLevel
	reviewedAt?: number
}

/**
 * Persistence for review decisions. The default implementation is per-browser
 * (`localStorage`); swap in a backend-backed one to make decisions team-wide.
 */
export interface ReviewStore {
	load(): Promise<Record<string, CapabilityReview>> | Record<string, CapabilityReview>
	save(reviews: Record<string, CapabilityReview>): Promise<void> | void
}

/** Policy configuration for {@link PolicyEngine}. */
export interface PolicyConfig {
	/**
	 * Execute `reversible` capabilities without asking.
	 * @default true
	 */
	autoApproveReversible?: boolean
	/**
	 * Execute `consequential` capabilities without asking.
	 * @default false
	 * @remarks Turning this on removes the only human gate in the pipeline.
	 */
	autoApproveConsequential?: boolean
	/** Capability names that may never run, whatever their risk level. */
	blocklist?: string[]
	/** When set, ONLY these capability names may run. */
	allowlist?: string[]
}
